### ISSUE TITLE
[Question] APT/PPA/deb/AppImage version ?

### ISSUE THREAD

**Issue by KaKi87** [tildeclub/ttrv#19]
Hello,

Since your fork seem to be the most popular of all, are you going to make compiled releases of it ?

Thanks !

**Comment by deepend-tildeclub** [comment]
No current plans on doing a distro specific release of it.  It is available via pip which should be fairly easy for most distros.

**Comment by KaKi87** [comment]
How do you run ttrv after installing it using pip ?

**Comment by deepend-tildeclub** [comment]
just by running 'ttrv'  in your terminal.

**Comment by KaKi87** [comment]
I get "command not found", how can I find out Python modules' binaries location path on my machine ? Thanks

**Comment by deepend-tildeclub** [comment]
One possibility is your system's python doesn't load by running python3
if that's the case  you can edit the file that runs ttrv and change it to python instead of python3
open this file in a text editor:  /usr/local/bin/ttrv 
change the #!/usr/bin/python3  to  #!/usr/bin/python
see if that helps.  
Either way ensure you have python3 installed and the 'python' command loads python3.
You can find that by running 'python -V'
