### ISSUE TITLE
Whats the difference between this and tuir?

### ISSUE THREAD

**Issue by dessalines** [tildeclub/ttrv#2]
https://gitlab.com/ajak/tuir/

**Comment by deepend-tildeclub** [comment]
Sorry for delayed reply.   As far as I can tell its basically just the same thing as this is.  A renamed fork of RTV.    I forked it in hopes that the community I am apart of would join efforts to keep RTV going.    Otherwise wanted to ensure there was always a place that users of RTV could request changes/updates to this code.  Since I doubt many pull requests will get dealt with on RTV anymore.
